server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul   #服务名字，也即注册到Eureka中的微服务名字

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527
    prefer-ip-address: true
security:  #配置访问 zuul 的 routes 的时候使用
  user:
    name: zuul
    password: zuul
zuul:
  prefix: /atguigu           #统一前缀
  ignored-services: "*"      #一般配置映射微服务名和路由路径都可以访问，配置这个忽略真实微服务名字，就是不让其通过微服务名来访问了，*代表忽略所有
  routes:
    MUYUPINGMICROSERVICE: /mydept/**        #映射的一种方式
    #mydept.serviceId: microservicecloud-dept
    #mydept.path: /mydept/**                #映射的第二种方式，保证mydept唯一即可
info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
